version: '3'
services:
  grafana:
    build:
      context: .
      dockerfile: GrafanaDockerfile
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - PROMETHEUS_HOST=prometheus
      - PROMETHEUS_PORT=9090
    ports:
      - "3000:3000"
  prometheus:
    image: prom/prometheus:v2.15.2
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  aiohttp:
    build:
      context: .
    environment:
      - CLIENT_ID=changeme
      - CLIENT_SECRET=changeme
    ports:
      - "80:80"
